server:
    port: 8081
example:
    property: DOCKER PROFILE

spring:
  jpa: 
    properties:
      hibernate: 
        ddl-auto: update
        show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://postgres-server:5432/spring
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: organization-service
  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic
      kafka:
        binder:
          zkNodes: localhost, kafka
          brokers: localhost, kafka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_URL}/eureka/

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
      health:
        enabled: true
        show-details: always
    health:
      db:
        enabled: false
      diskspace:
        enabled: true
